<?php

/**
 * @file
 * The Crop API Drupal module.
 *
 * Provides storage and API for image crops.
 */


/**
 * Implements hook_theme().
 */
function crop_theme() {
  return [
    'crop_crop_summary' => array(
      'variables' => array('data' => NULL, 'effect' => array()),
    ),
  ];
}

/**
 * Prepares variables for crop_crop summary template.
 *
 * Default template: crop-crop-summary.twig.html
 */
function template_preprocess_crop_crop_summary(&$variables) {
  $type = \Drupal::entityManager()->getStorage('crop_type')->load($variables['data']['crop_type']);
  $variables['data']['crop_type'] = $type->label();
}
